name: HACS Validation

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  hacs:
    name: HACS Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hacs/action@main
        with:
          category: integration
